openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /api/hello:
    get:
      summary: "GET api/hello"
      operationId: "hello"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
